### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by geddingj** [OSU-CS361-W17/group16_project1#13]
I'm making no progress on increasing test coverage still -- if anyone is making headway on that please submit a pull request so it can be viewed.

**Comment by geddingj** [comment]
I've tried several times to get an increase in test coverage and have come up with nothing of value. Hopefully one of you has had better luck with it because I need to sign off.

Also, since nobody has mentioned issues regarding the work I've submitted I'll assume that they are accomplishing what is desired. If problems do arise I'll say it again -- change what you need to.

**Comment by edwardne** [comment]
I worked on some of the test coverage and got it up a bit. I also changed a few things to make it easier to run the tests and fixed set hit and miss because the increment wasn't working. Sorry I didn't get back to you sooner.
