### ISSUE TITLE
“New model” Card

### ISSUE THREAD

**Issue by jiayuhan94** [OSU-CS361-W17/group16_project1#5]
As a user I want to have a new model so that I can play a new game without risk of overlap from previous iterations.
**Conversation:**

- [x]             -Create NewModel class to store ship stats
- [x]             -Have newModel() in main return a JSON string of stats
- [x]             -Have get/set functions for other functions

**Confirmation:**

- [x]             -Test default starting location for ships at start
- [x]             -Test to prevent JSON string from being null
- [x]             -Test 'get' functions for returning correct variable

**Comment by edwardne** [comment]
I was able to finish most of the testing

**Comment by jiayuhan94** [comment]
added some more test and just accept it myself. I got the coverage to 77%.
if u can get anymore improvement. that would be great.
